list1=set(["white","grey","red"])
list2=set(["red","violet"])
print("orginal set elements")
print(list1)
print(list2)
print("\n difference of list1 & list2:")
print(list1 - list2)
print("\n difference of ist2 & list1:")
print(list2-list1)
